#!/bin/bash

# Install extensions
# To generate => code --install-extension ahmadawais.shades-of-purple
code --install-extension akamud.vscode-theme-onedark
code --install-extension azemoh.theme-onedark
code --install-extension batisteo.vscode-django
code --install-extension brenosolutions.sqlformatter
code --install-extension donjayamanne.jupyter
code --install-extension donjayamanne.python-extension-pack
code --install-extension dunstontc.vscode-rust-syntax
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension HookyQR.beautify
code --install-extension magicstack.MagicPython
code --install-extension mauve.terraform
code --install-extension mohsen1.prettify-json
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension p1c2u.docker-compose
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust
code --install-extension seansassenrath.vscode-theme-superonedark
code --install-extension shardulm94.trailing-spaces
code --install-extension solomonsscott.furnace
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension WakaTime.vscode-wakatime
code --install-extension wholroyd.jinja
code --install-extension zhuangtongfa.Material-theme
code --install-extension ahmadawais.shades-of-purple
code --install-extension akamud.vscode-theme-onedark
code --install-extension azemoh.theme-onedark
code --install-extension batisteo.vscode-django
code --install-extension brenosolutions.sqlformatter
code --install-extension donjayamanne.jupyter
code --install-extension donjayamanne.python-extension-pack
code --install-extension dunstontc.vscode-rust-syntax
code --install-extension hnw.vscode-auto-open-markdown-preview
code --install-extension HookyQR.beautify
code --install-extension magicstack.MagicPython
code --install-extension mauve.terraform
code --install-extension mohsen1.prettify-json
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension p1c2u.docker-compose
code --install-extension PeterJausovec.vscode-docker
code --install-extension PKief.material-icon-theme
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust
code --install-extension seansassenrath.vscode-theme-superonedark
code --install-extension shardulm94.trailing-spaces
code --install-extension solomonsscott.furnace
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension WakaTime.vscode-wakatime
code --install-extension wholroyd.jinja
code --install-extension zhuangtongfa.Material-theme

ln -s $HOME/Documents/dotty/code/User $HOME/Library/Application\ Support/Code/User2